### ISSUE TITLE
Android sdk 中的so库咨询

### ISSUE THREAD

**Issue by zhanghan0616** [WildDogTeam/video-demo-android-conversation#1]
在Android 系统上，每一个CPU架构对应一个ABI：armeabi，armeabi-v7a，x86，mips，arm64- v8a，mips64，x86_64。而在 野狗云 中 只提供了 armeabi-v7a目录对应的so库文件，如果将这个so库文件放在其他的目录下，能否只支持相应的cpu架构的手机正常运行。

**Comment by anzeming** [comment]
目前预览版只支持arm cpu ，目前的版本是32-bit版，只能放在armeabi-v7a目录下，arm的32-bit 和64-bit架构cpu都可以使用。其余架构我们会在以后的版本中支持。目前大部分手机都是arm架构。
