### ISSUE TITLE
请问使用匿名认证失败是怎么回事。

### ISSUE THREAD

**Issue by zhanghan0616** [WildDogTeam/video-demo-android-conversation#2]
No value for code

**Comment by dongkai1993** [comment]
请检查一下控制面板中是否打开了允许匿名登录的开关。如果已经打开仍然失败，请提供更多错误信息

**Comment by zhanghan0616** [comment]
已开启允许匿名。
![image](https://cloud.githubusercontent.com/assets/8230482/20237004/75f4b098-a901-11e6-9814-08d77f742011.png)

![image](https://cloud.githubusercontent.com/assets/8230482/20237007/815bee60-a901-11e6-9adc-598925ae4b58.png)

**Comment by anzeming** [comment]
提供一下AppId，我帮你调试一下

**Comment by zhanghan0616** [comment]
zhiliaoyun

**Comment by anzeming** [comment]
请问你是否在控制面板中设置过Token过期时间呢？Token过期时间不能设置为0

**Comment by zhanghan0616** [comment]
1200月

**Comment by dongkai1993** [comment]
建议过期时间设为24小时较为合理，设置为1200月暂为无效设置

**Comment by zhanghan0616** [comment]
最大设置时长为多少呢，我们的是长期登录的

**Comment by zhanghan0616** [comment]
当前已设置为24小时，仍然认证失败的。匿名登录同样是 No value for code

**Comment by zhanghan0616** [comment]
好像使用token认证是可以了

**Comment by dongkai1993** [comment]
时间戳暂时只支持到2037年
通过上边的错误信息来看，JSON转string或string转JSON时报出的错误，能否提供一下具体报错的代码位置。

**Comment by zhanghan0616** [comment]
上面的日志图片上有具体报错代码的位置。

**Comment by anzeming** [comment]
请问你现在可以使用了么？

**Comment by zhanghan0616** [comment]
可以使用了

**Comment by zhanghan0616** [comment]
![image](https://cloud.githubusercontent.com/assets/8230482/20237359/84fba7d2-a90a-11e6-8c92-abf9729b3050.png)

好像使用token登录的方式还是有问题，匿名认证可以成功，使用token还是

**Comment by anzeming** [comment]
你是怎么获取token的呢？

**Comment by zhanghan0616** [comment]
我们的后端返回的token，ios上可以认证通过的

**Comment by anzeming** [comment]
qq：251193609,qq上说吧

**Comment by xiaoshagua213** [comment]
请问这个Demo运行能获取列表，但是邀请用户视屏聊天，接收不到邀请是怎么回事？

**Comment by xiaoshagua213** [comment]
![image](https://user-images.githubusercontent.com/24729217/30058570-288c2514-926e-11e7-90b3-67cdfc61186a.png)

**Comment by laufly** [comment]
@xiaoshagua213 你的网络环境是什么的呢.是否可以访问外网呢?应该是网络环境有问题导致获取配置信息失败

**Comment by zengchengjie** [comment]
对于网络环境不好导致连接断开的情况 有什么提示吗？还有一些其他意外情况。

**Comment by laufly** [comment]
@zengchengjie sdk内会尝试重连,直到超时,在错误中收到超时错误 41006
