### ISSUE TITLE
视频来源

### ISSUE THREAD

**Issue by zk0301** [WildDogTeam/video-demo-android-conversation#3]
1.前后摄像头切换，好像是switchCamera()
2.请问有没有屏幕截图做视频源，也就是ScreenCapturerAndroid。比如老师远程上课，老师要展示自己的手机屏幕。

**Comment by laufly** [comment]
@zk0301  目前只支持用照相机作为视频源,暂时不支持其他视频源.如果有需求,请联系商务.
联系方式:
工单地址 : https://wilddog.kf5.com/hc/request/new/

客服电话： 400-616-0980

客服邮箱：support@wilddog.com
