### ISSUE TITLE
android 一对一视频通话问题

### ISSUE THREAD

**Issue by zengchengjie** [WildDogTeam/video-demo-android-conversation#4]
请问android 一对一视频通话有时候不知道为什么接不到来电是为什么，已经确认的情况是网络状况良好，x86架构，5.0以上的系统，sdk版本：call 2.4.0。 sync2.3.7。auth:2.3.0。 多数情况可以接到，但有时候不知道为什么接不到来电请求，希望提供一个思路以便解决问题。谢谢

**Comment by laufly** [comment]
@zengchengjie  请确认下是否设置监听是在收到呼叫之前
